Repository nsu-null/NPidE, pull requests merged in 2022-05, with the labels that each got.

#12 Fix file creation + file opening + dirs and everything
  src/main/kotlin/ru/nsu_null/npide/ui/filetree/FileDialog.kt
  src/main/kotlin/ru/nsu_null/npide/ui/filetree/FileTree.kt
  src/main/kotlin/ru/nsu_null/npide/ui/filetree/FileTreeView.kt
Labels: enhancement

#10 Fix bugs related to build process
  CocoIDE-V1.91/cdm8_asm_build.py
  src/main/kotlin/ru/nsu_null/npide/ui/buttonsbar/ButtonActions.kt
Labels: bug

#9 Console with processes
  src/main/kotlin/ru/nsu_null/npide/ui/CodeViewer.kt
  src/main/kotlin/ru/nsu_null/npide/ui/CodeViewerView.kt
  src/main/kotlin/ru/nsu_null/npide/ui/ProjectView.kt
  src/main/kotlin/ru/nsu_null/npide/ui/buttonsbar/ButtonActions.kt
  src/main/kotlin/ru/nsu_null/npide/ui/console/Console.kt
  src/main/kotlin/ru/nsu_null/npide/ui/console/ConsoleView.kt
  src/main/kotlin/ru/nsu_null/npide/ui/npide/NPIDE.kt
Labels: documentation, enhancement, help wanted
